// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crm_importer.Data;

#nullable disable

namespace crmimporter.Migrations
{
    [DbContext(typeof(crm_importerContext))]
    partial class crm_importerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("crm_importer.Models.Lead", b =>
                {
                    b.Property<DateTime>("QuoteSentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalesPerson")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("raw")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuoteSentDate", "SalesPerson", "ProjectName");

                    b.ToTable("Lead");
                });
#pragma warning restore 612, 618
        }
    }
}
